### ISSUE TITLE
radar slam复现请教

### ISSUE THREAD

**Issue by MichaelSun1001** [dearmoonnnnnn/Notes#2]
您好！请问您使用的什么型号的radar复现4DRadarSLAM算法的呢？我也正在尝试复现中！

**Comment by dearmoonnnnnn** [comment]
你好，这边用的是德国大陆的 ars548，但建议使用原作者同款 Oculli Eagle

**Comment by dearmoonnnnnn** [comment]
是的，但目前效果并不好，后续还有改进空间
